name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 10 * *'

jobs:
  virus-total:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Build Binaries
        run: |
          make release-dry-run
      - name: List binaries
        run: |
          ls -lh ./dist/*/dstll
      - uses: dhth/composite-actions/.github/actions/scan-files@main
        with:
          files: './dist/*/dstll'
          vt-api-key: ${{ secrets.VT_API_KEY }}
